---
title: "Directory Code"
author: "Grace Rotondo"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(janitor)
library(base)
library(readxl)
library(ggplot2)
library(textclean)
library(leaflet)
library(purrr)
library(maps)
library(usmap)
library(sf)
library(fs)
library(leaflet)
library(tidyverse)
```

```{r}
#Merge the datasets and split the industries. This is necessary so that
#individuals within multiple industries can be searched  as an individual in one
#of the industries (not in a pair).
data <- full_join(alumnae, wlax, by = c('last_name', 'graduation_year', 'count')) %>% 
  mutate(industry = str_split(industry, ",")) 

#Separate the areas into city and state columns 
data_1 <- separate(data, area, into = c("city", "state"), sep = " (?=[^ ]+$)") %>% 
  mutate(clean_city = substr(city, 1, nchar(city)-1)) %>% 
  select(-city) %>% 
  rename(city = "clean_city")
```


```{r}
#Clean us_cities data
coords <- us_cities %>% 
  select(city_ascii, state_id, lat, lng) %>% 
  rename(city = "city_ascii",
         state = "state_id")
```

```{r}
#Merge data_1 with us_cities data to match the coordinates with the cities
full_data <- full_join(data_1, coords, by = c('city', 'state'))
```


```{r}
#Using leaflet to create the map.
#mymap <- mapStates = map("state", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% 
  addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)


#Prep location points for the map. See how many people are in each location.
location_points <- full_data %>% 
  group_by(city, state, lng, lat) %>% 
  count(city) %>% 
  arrange(desc(n))

#Mark clusters on map
leaflet(location_points) %>% 
  addTiles() %>% 
  addMarkers(
  clusterOptions = markerClusterOptions(
    showCoverageOnHover = TRUE
  )
  )
```




```{r}
#US map example 1
plot_usmap(data = statepop, values = "pop_2015", color = "darkblue") + 
  scale_fill_continuous(
    low = "white", high = "darkblue", name = "Population (2015)", label = scales::comma
  ) + theme(legend.position = "right")
```

```{r}
#US map example 2
plot_usmap(regions = "counties") + 
  labs(title = "US Counties",
       subtitle = "This is a blank map of the counties of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "lightblue"))
```





