#Create a search panel
checkboxInput("smooth", "Smooth"),
conditionalPanel(
  condition = "input.smooth == true",
  selectInput("smoothMethod", "Method",
              list("lm", "glm", "gam", "loess", "rlm"))
)


textInput(c("name", "first_name", "maiden_name", "last_name"), "Please enter a full, first, or last name")),
selectInput("industry", "Industry:",
            c("Finance" = "Finance",
              "Consulting" = "Consulting",
              "Law" = "Law",
              "Public Policy" = "Public Policy",
              "Hospitality" = "Hospitality",
              "Food & Beverages" = "Food & Beverages",
              "Non-Profit" = "Non-Profit",
              "Public Sector" = "Public Sector",
              "Cosmetics" = "Cosmetics",
              "Marketing" = "Marketing",
              "Health Care" = "Health Care",
              "Higher Education" = "Higher Education",
              "Real Estate" = "Real Estate",
              "Journalism" = "Journalism",
              "Technology" = "Technology",
              "Computer Software" = "Computer Software",
              "Media" = "Media",
              "Education" = "Education",
              "Sales" = "Sales",
              "Media Production" = "Media Production",
              "Music" = "Music",
              "Sports" = "Coaching")),

# Concentration Dropdown - input$industry (see Quantmod "concentration" argument")
selectInput("concentration", "Concentration:",
            c("Economics" = "Economics",
              "Government" = "Government",
              "Psychology" = "Psychology",
              "Statistics" = "Statistics",
              "Human Evolutionary Biology" = "Human Evolutionary Biology",
              "Biology" = "Biology",
              "Organismic & Evolution Biology" = "Organismic & Evolution Biology",
              "English & American Literature and Language" = "English & American Literature and Language",
              "Social Studies" = "Social Studies",
              "History" = "History",
              "History of Art & Architecture" = "History of Art & Architecture",
              "East Asian Studies" = "East Asian Studies",
              "Anthropology" = "Anthropology",
              "Physics" = "Physics",
              "Computer Science" = "Computer Science",
              "Neurobiology" = "Neurobiology",
              "Sociology" = "Sociology",
              "Musicology" = "Musicology")),
selectInput("house", "House:",
            c("Adams" = "Adams",
              "Cabot" = "Cabot",
              "Courier" = "Courier",
              "Dudley" = "Dudley",
              "Dunster" = "Dunster",
              "Eliot" = "Eliot",
              "Leverett" = "Leverett",
              "Kirkland" = "Kirkland",
              "Lowell" = "Lowell",
              "Mather"= "Mather",
              "Phorzheimer" = "Phorzheimer",
              "Quincy" = "Quincy",
              "South House" = "South House",
              "Winthrop" = "Winthrop"))),